travis:
  secure:
    BINSTAR_TOKEN: hixXGzGJXXddl9cP+bj3obt3M4p6kldqXqlQN7JIP7txZR8R472cEFNSvc+/RFVzZfvxpX6FTlRGf4dw58Nvzj47tftJTkZ3m+Ez69sQLjcUt/I3b+sgytv+nmk2+vKNIqN0zdoLDB1+2bQIIGzx+fg1RiDZGZixHMwppGueja46EoNAFLFtqegx5qL0JKMWjcY2fQpJRWhLxs00ZgXWssGHq73GFzb+TJNZJYFGgqpcWeeAypr+I9FCGSGaghcdcChN1mx7aI8FUQkRRKCYazP1AVM8AumYKnGg4kFah7Re+/cgkrZLaEJ47EMGeENDAwHSwNWyxu55TSzOcsSA/TYvxfg1dnEFke2u4OnzxgVlQo4s1m+RdKKvWiqBskxcc1u7yAYDQnYDsrepYsofY3OgO6o9SZ/py9/3Z8rInzNAvKc+Ih1MK5AzPqWavdRJubdiPrqmw99U8swKYujZBSNsTULLu6k7QtDOOpgtdgZEHppL1+Wk/oik+ZT4nfG7+FYdl5lbyxwBwM/BRshEfiec+4cUyugovzMYouxJ9yRwURBkcnEapBlZ/AaacxNhotNYLS22D4qNeOjlV8YBuBVEWRbMpDx2ekjAcTGVVFeU0WsBeIIBJXme/x1zJKIQtQhMsqIza7R2MZmIggLUIWC8quNVQxqwoTefLhkZYbE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
