travis:
  secure:
    BINSTAR_TOKEN: oOPH899pIAmIZogzzVgjNF2aYMpsKcNdxt/QvD5VqGSZe60FWrHiMdTTtB9MFI4MlClk0BT0f3s2DP+wWB46ZwujrTSZBCH8vlwTZr9p0hPjYVRDrZW69XYYUx6mtmOEIn6z9/cE5DApW9xa/1IS8Pg94wjfhPbVHLCJWNH87BGUR+BnpCKMeM2aqkpSfnwqHswi0wgEjMlZd22DiueOwPM17xmGlHzh/kwcTSdhCJgr18OrN7mWVF6N51W6TL2uSl0pO2msmWIHm7uiOsnsSlt5qHlL6HvBBovncgaFs6YOfZEzasVeExyhyAdjHRpCuESqKUiydmKzuJcBRhcVUP8l0/Vc8u1MGGPIRNs/yGQCv150Ipsq/y2Y4zBw0G2c+ug0CkqMNNEJKPethyL60c8IpCwdY1cyO+kxA6cJrthlzZBq2+ohc8D29AWcnrAKl8opYl0uSm4brVehl2bNZ0YdpDVbwmQo6sYkW79aBaayzUrjHyQO7j+y0roqrOvFn3SzQPB0rGKcUB42VK7e1cHaMLZmM7ea5vts0E16vUxbzKHvprDmbZ8h0+5yavsv6kfmrSXpSWZ0hy4/cxiwwFhK9wj4e1DxU4se3K/nvKGavDuSz7InCH//9iglP4g0VwbHPKMNA2w0NNlS9M97u7cSOR0NnsarxqxlGSWszfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
